Popup Window
sunga12/My-Portfolio pull request #11
Opened 2023-04-12 14:15 UTC by sunga12

- Works page built Dynamically
- Added Javascript for Featured project
- Added styling for popup window

2023-04-12 15:08 UTC, osamaashraf6 requested changes
Hi @sunga12 😊, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![SoCloseAlmostGIF](https://user-images.githubusercontent.com/83360636/231498653-c65fbf3a-85c7-4164-a7c2-be24bfcfb73d.gif)

## Highlights 🎉🚀
- [x] Not linter errors present💯
- [x] Good descriptive pull request
- [x] Nice design 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 15:08 UTC, osamaashraf6 commented on script.js
> +featSeeProject.innerHTML = '<h2>See Project<h2>';
- [ ] You did a great job 😃 at the popup, but I see that the style of the button here in the mobile version needs to be fixed to make it responsive with all screens, so let's fix the style here to make it like the Figma Design 😊💯

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Figma design | Your design| 
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/83360636/231492678-3838bb37-a788-4b59-8daf-a90db4100829.png)  |    ![image](https://user-images.githubusercontent.com/83360636/231492615-0a940806-8230-4e94-9fe6-fa8b5daedcdb.png)   |

2023-04-12 15:08 UTC, osamaashraf6 commented on script.js
> +
- [ ] While you make a great effort 😃 I see that I can't see all the popups because the size is big to see and it is disappearing on the page at the mobile version, so please try to fix that to make it like the Figma Design you can add vertical scroll to make the user can see all the popup content and with that, it will be nice 😊💯

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Figma design | Your design| 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/83360636/231494357-d7f3547e-5ae7-4502-982f-49a79f13dc39.png)    |   ![image](https://user-images.githubusercontent.com/83360636/231494294-93cf7073-e63b-4beb-a4a6-30662c0e1ef3.png)   |

2023-04-12 15:08 UTC, osamaashraf6 commented on index.html
- [ ] I see 😃 that below that code in vs code, there are a lot of unnecessary comments that make the code ugly, so please try to remove these comments because that's not from the best practice 💯 , so kindly try to remove these comments to make the code nice 😊

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Your code| 
| --- |
| ![image](https://user-images.githubusercontent.com/83360636/231496793-0d75177d-fa59-4965-8462-dd0affc618ce.png)   |

2023-04-12 15:08 UTC, osamaashraf6 commented on index.html
>  <section id="about" class="about">
- [ ] While you make a great effort 👌😃 I see that in the section about you used the h1 tag twice, so please 😃 try to use the h1 tag once time at the page as this for the best practice and to follow the best practice of using the semantics you can read more info [Here](https://www.w3schools.com/html/html5_semantic_elements.asp) to know how to apply the semantic tags 😊💯

> Check below to see the difference 😊⤵️
> If you can not see the image clearly just click on it to open a new tab in the browser😊

| Your Code | 
| --- |
|  ![image](https://user-images.githubusercontent.com/83360636/231498106-5ffd832d-2540-44f1-a27b-f27621fbca19.png)  |

2023-04-12 16:01 UTC, sunga12 commented on index.html
>  <section id="about" class="about">
Hi @osamaashraf6 Kindly explain this further. In my About section, I have only used the h1 tag once. kindly show where the other h1 tag is, thank you

2023-04-12 19:00 UTC, huseyinbiyik requested changes
Hi team,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif)

 ## Highlights
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- .gitignore used to ignore requested files 📁
- PR description is descriptive 📝


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML"
<img width="444" alt="Screenshot 2023-04-12 at 10 00 09 PM" src="https://user-images.githubusercontent.com/25887253/231558342-ea99941d-113e-4272-bf48-c510a0f03591.png">

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 19:00 UTC, huseyinbiyik commented on script.js
> +// featSeeProject.style.width = '30%';
Please don't leave any uncommented code in your codebase. In this way, you can keep your codebase neat, organized and professional..

2023-04-12 19:00 UTC, huseyinbiyik commented on styles.css
> +
As the previous reviewer requested, the design needs to look like the Figma template. Kindly align the icons and text horizontally well. Currently icons are a bit on a higher position than text 🗻 
<img width="594" alt="Screenshot 2023-04-12 at 9 43 57 PM" src="https://user-images.githubusercontent.com/25887253/231555932-c4056eb7-d9ec-4b50-94aa-a151689cb222.png">
<img width="444" alt="Screenshot 2023-04-12 at 9 44 14 PM" src="https://user-images.githubusercontent.com/25887253/231555935-c8a0a673-2c0d-47fe-ae3a-c51644d160fd.png">

2023-04-12 19:00 UTC, huseyinbiyik commented on script.js
> +});
[OPTIONAL] Your code works well but it is not following the best practice in terms of DRY. You have so many repeating line in your code that needs to be refactored. I recommend you use template literals strings and use loops to render it. You can check this [repo](https://github.com/huseyinbiyik/huseyinbiyik.github.io/blob/main/script.js) to get inspired. 💠

2023-04-13 08:36 UTC, KayLemba approved these changes
[[# STATUS: APPROVED :green_circle: :clap: 

Hello @sunga12         , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: a
Congratulations! 🎉  Keep up the good work 🥂 

HIGHLIGHTS:

- [x]  Your repo is professional  😎 
- [x] Descriptive P.R 💯 
- [x] Professional README 💯
- [x] Your work is well documented 🥇 
- [x] Nice UI design   🥇   











 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]]s

2023-04-13 08:47 UTC, merged