Finish Mobile Version: Recent works & About me page
sunga12/My-Portfolio pull request #2
Opened 2023-03-24 10:54 UTC by sunga12

- Added Recent Works page

2023-03-24 15:19 UTC, AHP15 requested changes
Hi @sunga12 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![soclose](https://user-images.githubusercontent.com/97100091/199273222-010c4c63-4b9f-4149-9cac-ca9dde88e551.gif)
## Highlights
✅ Great design
✅ No linter errors
✅ Good GitHub flow

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 15:19 UTC, AHP15 commented on styles.css
> +button.project-link-btn {
- [ ] Kindly make sure that the alignment of the text in this button is matching the design:

 ## Your design:
![s2](https://user-images.githubusercontent.com/95412943/227566253-6620c497-1e47-4dff-8b51-f7ae25b6f377.PNG)

## Figma design

![s](https://user-images.githubusercontent.com/95412943/227566328-a97e2024-7c25-48df-ab97-43d2c030755b.PNG)

2023-03-24 17:18 UTC, PinkMoon25 requested changes
Hi @sunga12 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights
Linter checks :heavy_check_mark: 
github flow :heavy_check_mark: 
flex and grid :heavy_check_mark: 
follows figma template :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-24 17:18 UTC, pinkmoon25 commented on styles.css
> +}
- [ ] Good job making the changes requested by the previous reviewer, I think there was a bug introduced while making the changes, please see that the project card is not visible properly and the bottom of the button is cut out :point_down: 
![image](https://user-images.githubusercontent.com/97521557/227595188-11cd2a32-f3d5-4642-8d04-fcec80b5a211.png)

I suggest loosing the fixed height property that you have set on the project cards please try to fix it :+1:

2023-03-25 07:27 UTC, PinkMoon25 approved these changes
Hi @sunga12 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Linter checks :heavy_check_mark: 
GitHub flow :heavy_check_mark: 
flex and grid :heavy_check_mark: 
follows figma template :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 07:45 UTC, merged